### ISSUE TITLE
Los nombres de los archivos sobresalen en las pestañas si son muy largos

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/codeEditor2#1]
![image 2018-02-05 13 29 18](https://user-images.githubusercontent.com/16567802/35804558-92402000-0a78-11e8-8bbd-d71887b5ad12.jpg)

**Comment by joaquinaraujo** [comment]
Cree una función que limita una cadena de textos y al final le agrega unos puntos suspensivos (que indica que el nombre continua)

**/src/editor-dev/utils.js**
```
// Puntos suspensivos para los nombres largos en las pestanas
function ellipsis(text, limit) {
  if(text.length > limit) {
    return `${text.substring(0,limit)}...`
  }
  return text
}
```

Un ejemplo de uso seria:

`ellipsis('untitled-untitled', 12)`

El resultado es el siguiente:

![image](https://user-images.githubusercontent.com/20958348/35912071-eb995dce-0bd1-11e8-98c7-b0c384a6b51c.png)

**Comment by icastillejogomez** [comment]
fixed
