### ISSUE TITLE
Mostrar errores de forma correcta al usuario si las diversas acciones fallan. 

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/codeEditor2#10]
Pregúntale a @jorge9200  como usar la funcionalidad multi-idioma.

**Comment by joaquinaraujo** [comment]
Ya le he preguntado y me ha respondido, quedo pendiente en mostrar los mensajes.
https://github.com/Inevio/codeEditor2/issues/5#issuecomment-365927835

**Comment by joaquinaraujo** [comment]
![image](https://user-images.githubusercontent.com/20958348/36438675-fe7ccf10-1640-11e8-9346-7973b1ec1588.png)

Ya el editor esta configurado con `lang` :)

**Comment by icastillejogomez** [comment]
Vuelvo a abrir porque esto no esta probado.

**Comment by joaquinaraujo** [comment]
Por favor prueba esta Issues
