### ISSUE TITLE
Todas estas opciones no se despliegan ni hacen nada

### ISSUE THREAD

**Issue by jorge9200** [Inevio/codeEditor2#11]
![image](https://user-images.githubusercontent.com/8724844/36422126-385895a8-163b-11e8-8132-c5982d5e4eaa.png)

**Comment by joaquinaraujo** [comment]
Por favor @jorge9200, pasame el listado de sub-opciones para agregarlas dentro de cada menu :)

**Comment by jorge9200** [comment]
Realmente lo que hay que hacer es que toda funcionalidad que se pueda accionar por comando tambien se pueda por menú. Los menús que queden vacios por que no tengan funcionalidades se ocultan y listo!

Para ocultarlos deja metido una pequeña comprobacion de si el contenido es 0 y listo

**Comment by joaquinaraujo** [comment]
Listo, ahora solo se muestran las opciones que tienen submenus!
https://imgur.com/BhScfly
