### ISSUE TITLE
Error en el menu del sidebar

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/codeEditor2#13]
Si hago "Open folder" de la carpeta raíz de mi horbito y luego en el explorador hago click derecho sobra la carpeta "Home" me muestra las opciones "Rename" y "Delete" las cueles no se pueden efectuar sobre la carpeta "Home".

![image](https://user-images.githubusercontent.com/16567802/36579916-14a746cc-1866-11e8-99f9-4c195e545aa0.png)

Como ves en la foto no se tiene en cuenta este caso, deberías mirar si es la carpeta "Home" y no mostrar dichas opciones. :)

**Comment by joaquinaraujo** [comment]
![image](https://user-images.githubusercontent.com/20958348/37352351-6c66a992-26b3-11e8-8864-ada36252c1ff.png)

1. Solo en la carpeta raiz aparece la opcion de "Cerrar carpeta"
2. En las carpetas especiales del sistema no aparece la opcion de "Eliminar ni Renombrar"
3. En el resto de carpetas NO ESPECIALES aparecen todas las opciones menos la de cerrar (que solo aparece en la raiz)

**Comment by icastillejogomez** [comment]
En las carpetas "raiz" como tus las llamas no aparece la opción de rename.

**Comment by icastillejogomez** [comment]
El rename aparece a veces y a veces no, míralo bien.

**Comment by icastillejogomez** [comment]
Cierro ya que he abierto una issue especifica del rename.
