### ISSUE TITLE
Cuando hago "new file" con click derecho en una carpeta no hace nada

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/codeEditor2#16]
Pues eso, cuando en el explorador de la izq hago click derecho en una carpeta y selecciono archivo nuevo no pasa nada. Cuando hago nueva carpeta todo bien.

**Comment by joaquinaraujo** [comment]
Hace falta solucionar el save para poder crear archivos :)

**Comment by icastillejogomez** [comment]
Cierro y la relaciono con la issue de "save"
