### ISSUE TITLE
Cuando hago click derecho en una carpeta no aparece la opción de borrar.

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/codeEditor2#17]

**Comment by joaquinaraujo** [comment]
Cuando la carpeta no es una "carpeta especial de Horbito (type 0 or 1)" aparecen las opciones:
https://imgur.com/a/QBIKO

Cuando la carpeta SI ES UNA CARPETA ESPECIAL DE HORBITO, no aparecen las opciones de "eliminar ni renombrar"
https://imgur.com/3BAFnsu

**Comment by icastillejogomez** [comment]
type === 0 'Es la carpeta que tiene la raíz de tu Files' (La que tu nombras 'Home' en el explorador)
type === 1 'Carpeta especial de horbito: Cosmos, Documents, Music, etc'
type === 2 'Carpeta normal del usuario'
type === 3 'Archivo'
