### ISSUE TITLE
Necesitamos el logo de esta parte de la app

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/codeEditor2#18]
![image](https://user-images.githubusercontent.com/16567802/37375502-29313ff8-2720-11e8-95ab-727a19ffc362.png)

**Comment by tavi004** [comment]
![favicon](https://user-images.githubusercontent.com/3248361/37667767-1537e306-2c63-11e8-8ade-542eebd9e407.png)
![favicon 2x](https://user-images.githubusercontent.com/3248361/37667768-15532f44-2c63-11e8-95bb-774c970a841a.png)

**Comment by icastillejogomez** [comment]
Perfecto, se la asigno a Joaquin para que lo ponga 😸

**Comment by icastillejogomez** [comment]
Cierro
