### ISSUE TITLE
La opción de rename no aparece en las carpetas a veces.

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/codeEditor2#19]

**Comment by joaquinaraujo** [comment]
Rename y Delete solo aparece en las carpetas !== 0 y !== 1 (es decir, las carpetas NO especiales de Horbito) y en las "raices", lo que puedo hacer es que en las "raices" que no sean carpetas especiales de Horbito se permita el Rename y Delete, de resto Horbito no permite ni eliminar ni renombrar las carpetas especiales (hasta donde tenga entendido)

**Comment by joaquinaraujo** [comment]
Te escribo lo mismo que aca https://github.com/Inevio/codeEditor2/issues/17#issuecomment-372868636

**Comment by icastillejogomez** [comment]
Justo, la raiz tiene que poder hacer delete y rename si no es especial
