### ISSUE TITLE
no se quita el focus CSS después de buscar

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/codeEditor2#2]
![image](https://user-images.githubusercontent.com/16567802/36073475-8fdde99c-0f31-11e8-9903-3b2a0271203a.png)

Cuando cierro buscar no se quita el focus.

**Comment by joaquinaraujo** [comment]
Ya puedes realizar una busqueda de texto:

![image](https://user-images.githubusercontent.com/20958348/36403466-65bfd626-15bb-11e8-869d-e1bc4cbeedd5.png)

Y al hacer click sobre CodeMirror desaparecerá el marcado Amarillo :)

![image](https://user-images.githubusercontent.com/20958348/36403491-88188dbc-15bb-11e8-8797-edf491ed1442.png)

**Comment by icastillejogomez** [comment]
fixed
