### ISSUE TITLE
Los archivos han de abrirse han hacerles doble click

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/codeEditor2#3]
Además, desde que hago el doble click hasta que llega la respuesta deberías mostrar un mensaje de cargando....

**Comment by joaquinaraujo** [comment]
He solucionado el doble-click, y eliminado el click-largo, ahora solo basta con hacer doble-click para desplegar una carpeta sin problemas.

Me parece buena idea lo del mensaje "cargando" pero propongo hacerlo con un icono para que quede mas bonito, consegui este:

![image](https://media.giphy.com/media/12yixaK3jASpb2/giphy.gif)

...pero me gustaría que fuera el logo de Horbito para que se complemente mejor, que opinas al respecto?

**Comment by icastillejogomez** [comment]
fixed
