### ISSUE TITLE
Bug al listar los archivos

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/codeEditor2#4]
Esto es lo que te he pasado por Telegram. Se soluciona no dejándome colapsar las carpetas hasta que ha llegado la respuesta. 

Video: http://wz.io/f/aEcHsXhL

**Comment by joaquinaraujo** [comment]
![image](https://user-images.githubusercontent.com/20958348/36275233-a658014e-1260-11e8-890e-0b59ef34d5f3.png)

Ignacio, por favor, prueba nuevamente, he aumentado los tiempos de espera a 700 milisegundos y ajustado a un doble-click o un click-largo (este problema surge de que al realizar un click y dejarlo pegado JS suma los clicks++) con el fin de evitar que las flechas indiquen que la carpeta se cerro, cuando la verdad eso no ha pasado.

**Comment by icastillejogomez** [comment]
fixed
