### ISSUE TITLE
Cuando borro un archivo usando el menu contextual no me pregunta si estoy seguro

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/codeEditor2#5]
Para hacer esto, como ya sabes debes usar el método confirm:

    confirm( 'Estas seguro?', ( response ) => {

        if( response ) {

            /* User accept erase */

        }
        else{

            /* Do nothing */

        }

    })

![image](https://user-images.githubusercontent.com/16567802/36254332-0b35c9f4-124b-11e8-82ab-7426f9b51b4e.png)

**Comment by icastillejogomez** [comment]
Aquí ya deberías usar multi-idioma y poner un mensaje del tipo "¿Estas seguro que desea borrar el archivo/carpeta ${nombreArchivoCarpeta} ?

**Comment by jorge9200** [comment]
@JoaquinAraujo para usar multidioma genera una carpeta lang en la raiz de tu app y genera tantos .json como idiomas desees. Luego podras acceder a esos jsons desde tus scripts usando la variable lang

mira alguna de nuestras apps como ejemplo https://github.com/Inevio/Cosmos/

**Comment by joaquinaraujo** [comment]
![image](https://user-images.githubusercontent.com/20958348/36285427-e437eea4-1281-11e8-9956-3c8aaed23a89.png)
