### ISSUE TITLE
La opción de rename debería estar también en 'Edit'

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/codeEditor2#6]

**Comment by icastillejogomez** [comment]
![image](https://user-images.githubusercontent.com/16567802/36254517-af6a7952-124b-11e8-8d8d-5097b2da0fdc.png)

**Comment by joaquinaraujo** [comment]
![image](https://user-images.githubusercontent.com/20958348/36296866-dc546016-12c5-11e8-8328-f547445c0bea.png)

Ignacio, estuve mirando Sublime Text y no contiene esa opción en su menu Edit, crees que esta bien implementarla (tomando en cuenta los pasos de los grandes)?

**Comment by icastillejogomez** [comment]
Te costaría mucho añadirla?

**Comment by icastillejogomez** [comment]
Debería afectar a la pestaña que tiene focus. Si no hay pestañas abiertas debería salir un alert diciendolo, no hay pestañas abiertas.

**Comment by joaquinaraujo** [comment]
![image](https://user-images.githubusercontent.com/20958348/37431427-9fc21800-27ab-11e8-9adf-7b2dcda896de.png)

No solo la mejora de "renombrar desde el menu", sino que también implemente la función de "eliminar", estas mejoras se encuentran sincronizadas con el Sidebar, es decir, que si se renombra o elimina un archivo se vera afectado en el Sidebar automáticamente o en caso de hacerlo desde el Sidebar (eliminar o renombrar un archivo) los cambios se reflejaran en las pestañas (si se renombro el archivo) o en cerrando dicho archivo eliminado (tal como pasa en SublimeText)

**Comment by icastillejogomez** [comment]
Cierro
