### ISSUE TITLE
Mejora al general el menu principal

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/codeEditor2#7]
![image](https://user-images.githubusercontent.com/16567802/36254553-cff794fc-124b-11e8-86ca-e29154c557e9.png)

Si un menu no tiene opciones no tiene sentido renderizarlo. Como el menu es un objeto JSON para ti debería ser fácil mirar el length de submenus y si es cero no renderizarlo. 

Una buena mejora sería añadir un atributo hidden al cada menu para que el programa al renderizar lo ignore. Por ejemplo, si pones hidden true en File aunque tenga submenus no lo renderize, util para cuando has hecho un menu y quieres que no se renderize pero no quieres borrarlo del JSON ;)

**Comment by joaquinaraujo** [comment]
![image](https://user-images.githubusercontent.com/20958348/36296657-b441fc38-12c4-11e8-8893-51b010ec04c0.png)

Ya eso se puede hacer pero de una forma muchísimo mas sencilla, simplemente se usan los comentarios de tipo bloque y gracias a WebPack el **archivo-final.js** queda limpio de ellos e incluso hasta de espacios, en conclusion: Optimizado para producción :smile:

**Comment by icastillejogomez** [comment]
Eso es una chapuza, es mucho más fácil cambiar un `display: true` por un `display: false` y en el bucle que lo imprimes (si es un for loop normal) `if( !elem.display ) continue()` y ya esta. Reabro.
