### ISSUE TITLE
La carpeta a la que hago "Open folder" no se puedo hacer "Close folder" 

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/codeEditor2#8]
Dejo una foto para que veas que no me das la opción

![image](https://user-images.githubusercontent.com/16567802/36254668-2ef000c0-124c-11e8-917a-87a112d21a85.png)

**Comment by joaquinaraujo** [comment]
![image](https://user-images.githubusercontent.com/20958348/36276498-8f809d60-1264-11e8-93f5-a5046c8d6b96.png)

1. Imaginas algo así o en el ContextMenu?
2. En todas las carpetas o solo en la carpeta "Raíz" (en la que se abre)?

**Comment by joaquinaraujo** [comment]
![image](https://user-images.githubusercontent.com/20958348/36405629-0dccd376-15c8-11e8-9cce-38e9e7ee639c.png)

Dada la espera he intuido que era de colocar la opción en el ContextMenu

**Comment by icastillejogomez** [comment]
Debería estar solo en la raíz. Reabro.
