### ISSUE TITLE
Cambiar el tamaño del texto con atajos de teclado

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/codeEditor2#9]
Estaría bien que capturas como haces con los otros atajos los típicos para agrandar o disminuir el tamaño del texto 😄

**Comment by jorge9200** [comment]
una vez hecho molaria meterlo tambien en el menu de arriba 'Edit'

**Comment by joaquinaraujo** [comment]
Se agrego la mejora de los atajos de teclado para aumentar y disminuir la fuente del editor
![image](https://user-images.githubusercontent.com/20958348/37647888-d1396d6e-2c03-11e8-9d52-a80653760a52.png)

No se puede usar **Cntrl + +** ni Cntrl + - porque ya estan reservados para el navegador

Las combinacion de teclas que coloque fueron:
**CNTRL + M** Aumentar tamano de fuente
**CNTRL + N** Reducir tamano de fuente

Tambien fue incluido en el menu
![image](https://user-images.githubusercontent.com/20958348/37647845-aafc13fe-2c03-11e8-8c8b-6e7ca82421d8.png)

**Comment by icastillejogomez** [comment]
Okay pues entonces pon como hacen todos los programas del mundo el atajo alineado a la derecha

**Comment by icastillejogomez** [comment]
Y metelo en un menu de "Ver" siguiente a "Editar"

![image](https://user-images.githubusercontent.com/16567802/37653590-b9f97ec8-2c3f-11e8-81e7-5d6ed2a13240.png)

**Comment by icastillejogomez** [comment]
A esto me refiero 

![image](https://user-images.githubusercontent.com/16567802/37657387-1aba112c-2c4b-11e8-9c90-4ef612ed111d.png)

**Comment by joaquinaraujo** [comment]
![image](https://user-images.githubusercontent.com/20958348/37695254-59e90f16-2ca4-11e8-9055-ddefd8c2e59f.png)

Con gusto Ignacio ;)

**Comment by icastillejogomez** [comment]
Hecho. Cierro.
